# Generated by Django 2.0.5 on 2018-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20180610_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_complete',
            field=models.BooleanField(default=False),
        ),
    ]
