# Generated by Django 2.0.5 on 2018-06-20 07:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_exam_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
