# Generated by Django 2.0.5 on 2018-06-20 07:26

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20180620_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
