# Generated by Django 2.0.5 on 2018-12-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20180620_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='vote',
            new_name='downvote',
        ),
        migrations.AddField(
            model_name='question',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
