# Generated by Django 2.0.5 on 2018-12-16 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0012_auto_20181216_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_title', models.CharField(blank=True, max_length=256, null=True)),
                ('feedback_body', models.TextField()),
                ('feedback_type', models.CharField(choices=[('wrong_answer', 'Wrong Answer'), ('improvement', 'Improvement')], max_length=128)),
                ('user_email', models.EmailField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
