# Generated by Django 2.0.5 on 2018-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_answerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerfeedback',
            name='feedback_status',
            field=models.CharField(choices=[('received', 'Received'), ('reviewing', 'Reviewing'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='received', max_length=128),
        ),
    ]
