# Generated by Django 2.0.5 on 2018-12-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_answerfeedback_feedback_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerfeedback',
            old_name='time',
            new_name='created',
        ),
        migrations.AddField(
            model_name='answerfeedback',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
