# Generated by Django 2.0.5 on 2018-06-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_exam_complete'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='questions',
            field=models.ManyToManyField(to='exams.Question'),
        ),
    ]
