# Generated by Django 2.0.5 on 2018-08-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_auto_20180610_1447'),
        ('users', '0002_user_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='universities.University'),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
