# Generated by Django 2.0.5 on 2018-12-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_auto_20181216_1029'),
        ('users', '0004_auto_20181216_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='voted_questions',
        ),
        migrations.AddField(
            model_name='user',
            name='downvoted_questions',
            field=models.ManyToManyField(related_name='downvoted_questions', to='exams.Question'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_questions',
            field=models.ManyToManyField(related_name='upvoted_questions', to='exams.Question'),
        ),
    ]
