# Generated by Django 2.0.5 on 2018-12-18 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_auto_20180610_1447'),
        ('users', '0005_auto_20181216_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='universities.Course'),
        ),
    ]
