# Generated by Django 2.0.5 on 2018-05-29 16:25

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20180529_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=config.utils.upload_university_cover_path),
        ),
    ]
