# Generated by Django 2.0.5 on 2018-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_auto_20180531_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=128),
        ),
    ]
